name: GitHub Actions Pr to master
on:
  pull_request:
  push:
    branches: master
jobs:
  on_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Lint checks
        run: npm run lint
      - name: Prettier checks
        run: npm run prettier
      - name: Unit tests
        run: npm test

      - name: Upload E2E Test Report Artifact
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: scripterio-report
          path: scripterio-report/
          retention-days: 30
